# .rubocop.yml

require: rubocop-rake

AllCops:
  NewCops: enable

  Exclude:
    - 'bin/**'
    - 'config.ru'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/201*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Max: 100

Layout/LineLength:
  Max: 180

Style/Documentation:
  Enabled: false
